# Generated by Django 4.0.3 on 2022-04-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='id',
        ),
        migrations.AlterField(
            model_name='family',
            name='document',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
